# Generated by Django 5.2.7 on 2025-11-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
